###
GET http://localhost:8081/api/productos.php
###
GET http://localhost:8081/api/categorias.php
###
GET http://localhost:8081/api/ofertas.php

### Añadir producto al carrito
POST http://localhost:8081/api/carrito_add.php
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWJyZSI6ImFsZXhhbmRyYSIsInJvbCI6ImNsaWVudGUiLCJpYXQiOjE3Njk3Njk5MTAsImV4cCI6MTc2OTc3NzExMH0.g9RarUNAsLObNAcbqvSgoTjQtEDyPLLSxfmLcJ5wOVY

{
  "productoId": 2
}

### Obtener carrito de un usuario
POST http://localhost:8081/api/carrito_get.php
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWJyZSI6ImFsZXhhbmRyYSIsInJvbCI6ImNsaWVudGUiLCJpYXQiOjE3Njk3Njk5MTAsImV4cCI6MTc2OTc3NzExMH0.g9RarUNAsLObNAcbqvSgoTjQtEDyPLLSxfmLcJ5wOVY

### Añadir pedido
POST http://localhost:8081/api/pedido_add.php
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsIm5vbWJyZSI6ImFsZXhhbmRyYSIsInJvbCI6ImNsaWVudGUiLCJpYXQiOjE3Njk3Njk5MTAsImV4cCI6MTc2OTc3NzExMH0.g9RarUNAsLObNAcbqvSgoTjQtEDyPLLSxfmLcJ5wOVY

{
  "productos": [1, 4, 4, 5]
}

### Obtener pedidos de un usuario
GET http://localhost:8081/api/pedidos_get.php
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWJyZSI6ImFkbWluIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3Njk3MDM4MDcsImV4cCI6MTc2OTcxMTAwN30.bT5RUXpDqcJmmLbddT7iG4kitXQ1pdl3D4DTytKskks

### Obtener información de usuario
GET http://localhost:8081/api/usuario.php
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5vbWJyZSI6ImFkbWluIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NjkwMTMzMzYsImV4cCI6MTc2OTAyMDUzNn0.P6P6JyFVnv7Aq-0AtzhP8r-qEiijo9C_O91cMrfd6X0
